config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

  devise_for :accounts,controllers: {
    sessions: 'accounts/sessions',
    password: 'accounts/passwords',
    registrations: 'accounts/registrations',
    confirmations: 'accounts/confirmations'
  }
  
  root "restaurants#index"

  resources :restaurants do
    resources :tables
    resources :menu_items
  end


post "restaurant/:id/reservations/index" , to: "reservations#index" , as:"reservation_index"

delete "restaurant/:id/reservations/:reservation_id/order", to: "orders#destroy" , as:"reservation_order_delete"

#table booking
  get "restaurant/:id/reservations/:type" , to: "table_bookeds#table" , as:"reservation_table"
  post "restaurant/:id/reservations/:type/confrim", to: "table_bookeds#confrim" , as:"reservation_table_confrim"
  get "reservations/show" , to: "table_bookeds#show" , as:"reservation_show"
  delete "restaurant/:id/reservations/:reservation_id", to: "table_bookeds#destroy" , as:"reservation_table_delete"
  delete "restaurant/:id/reservations/:reservation_id/:table_id", to: "table_bookeds#destroy_each" , as:"reservation_table_each_delete"
  get "restaurant/:id/today" , to: "table_bookeds#today_table" , as:"today_tables"
  post "restaurant/:id/today_confrim" , to: "table_bookeds#today_table_confrim" , as:"today_tables_confrim"

  get "restaurant/:id/reservations/:reservation_id/edit" , to: "table_bookeds#edit" , as:"reservation_table_edit"
  post "restaurant/:id/reservations/:reservation_id/update" , to: "table_bookeds#update" , as:"reservation_table_update"

#food ordering
  get "restaurant/:id/reservations/:reservation_id/food" , to: "orders#food" , as:"reservation_food"
  post "restaurant/:id/reservations/:reservation_id/food/confrim", to: "orders#confrim" , as:"reservation_food_confrim"
  get "restaurant/:id/reservations/:reservation_id/order/edit" , to: "orders#edit" , as:"reservation_order_edit"
  patch "restaurant/:id/reservations/:reservation_id/order/update" , to: "orders#update" , as:"reservation_order_update"

 #order items 

  delete "restaurant/:id/reservations/:reservation_id/order/:order_item_id", to: "order_items#destroy" , as:"reservation_order_items_delete"
  post "restaurant/:id/reservations/:reservation_id/order/:order_id/new", to: "order_items#new" , as:"reservation_order_items_new"

  #ratings
  get "restaurant/:id/reservations/:reservation_id/rating" , to:"ratings#new" , as:"reservation_rating_new"
  post "restaurant/:id/reservations/:reservation_id/rating_create" , to:"ratings#create" , as:"reservation_rating_create"
   
  # for api

  namespace :api ,default: {format: :json} do
  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    

    devise_for :accounts,controllers: {
      sessions: 'accounts/sessions',
      password: 'accounts/passwords',
      registrations: 'accounts/registrations',
      confirmations: 'accounts/confirmations'
    }
    
    root "restaurants#index"

    resources :restaurants do
      resources :tables
      resources :menu_items
    end


  post "restaurant/:id/reservations/index" , to: "reservations#index" , as:"reservation_index"

  delete "restaurant/:id/reservations/:reservation_id/order", to: "orders#destroy" , as:"reservation_order_delete"

  #table booking
    get "restaurant/:id/reservations/:type" , to: "table_bookeds#table" , as:"reservation_table"
    post "restaurant/:id/reservations/:type/confrim", to: "table_bookeds#confrim" , as:"reservation_table_confrim"
    get "reservations/show" , to: "table_bookeds#show" , as:"reservation_show"
    delete "restaurant/:id/reservations/:reservation_id", to: "table_bookeds#destroy" , as:"reservation_table_delete"
    delete "restaurant/:id/reservations/:reservation_id/:table_id", to: "table_bookeds#destroy_each" , as:"reservation_table_each_delete"

    get "restaurant/:id/reservations/:reservation_id/edit" , to: "table_bookeds#edit" , as:"reservation_table_edit"
    post "restaurant/:id/reservations/:reservation_id/update" , to: "table_bookeds#update" , as:"reservation_table_update"

  #food ordering
    get "restaurant/:id/reservations/:reservation_id/food" , to: "orders#food" , as:"reservation_food"
    post "restaurant/:id/reservations/:reservation_id/food/confrim", to: "orders#confrim" , as:"reservation_food_confrim"
    get "restaurant/:id/reservations/:reservation_id/order/edit" , to: "orders#edit" , as:"reservation_order_edit"
    patch "restaurant/:id/reservations/:reservation_id/order/update" , to: "orders#update" , as:"reservation_order_update"

  #order items 

    delete "restaurant/:id/reservations/:reservation_id/order/:order_item_id", to: "order_items#destroy" , as:"reservation_order_items_delete"
    post "restaurant/:id/reservations/:reservation_id/order/:order_id/new", to: "order_items#new" , as:"reservation_order_items_new"

    #ratings
    get "restaurant/:id/reservations/:reservation_id/rating" , to:"ratings#new" , as:"reservation_rating_new"
    post "restaurant/:id/reservations/:reservation_id/rating_create" , to:"ratings#create" , as:"reservation_rating_create"
    

    #custom api

    get "restaurant/:city", to:"restaurants#restaurant_city"
    get "highest_reservation" , to:"restaurants#restaurant_highest_reservations"
    get "restaurant/:id/users" , to: "restaurants#restaurant_users"
    get  "highest_order" , to:"orders#highest_item"
    get "highest_reservation/user" , to:"restaurants#highest_reservation_user"
    
  end

end

app/models/table_booked.rb
class TableBooked < ApplicationRecord
    belongs_to :reservation
    validates :name , :table_id , presence:true
end

app/controllers/api/table_bookeds_controller.rb
class Api::TableBookedsController < Api::ApiController

    # before_action :authenticate_account!
    
    before_action :is_user , only: [:table,:confrim,:edit,:update,:destroy,:destroy_each]

    before_action :is_user_table , only: [:edit,:update,:destroy,:destroy_each]


    def table 
        restaurant = Restaurant.find_by(id: params[:id])
        if restaurant
            tables = restaurant.tables
            type = params[:type]
            if tables
                unless type=="table" or type=="food" or type=="table_food"
                    render json: {message:"Invalid type"} , status: :unprocessable_entity
                    return
                end
                render json: tables , status: :ok
                return
            else
                render json: {message:"No table is found for restaurant with this id #{params[:id]}"}, status: :no_content
                return
            end
        else 
            render json: {message:"No restaurant is found with this id #{params[:id]}"}, status: :not_found
            return

        end
    end

    def confrim
        restaurant = Restaurant.find_by(id: params[:id])
        if restaurant
            tables = restaurant.tables 
            type = params[:type]
            date = params.require(:date_id)
            
            unless type=="table" or type=="food" or type=="table_food"

                render json: {message:"Invalid type"} , status: :unprocessable_entity
                return
            else
                if tables

                    if date and date[:date].length!=0
                        reservations = Reservation.where(restaurant_id:restaurant.id)
                        flag=0
                        
                        if date.present? &&  Date.parse(date[:date])< Date.today

                            render json: {message:"Date can't be in past"} , status: :unprocessable_entity
                            return
                        else 
                            if reservations && reservations.each do |reservation|
                                if reservation.date.to_s == date[:date].to_s
                                    if reservation.tables && reservation.tables.each do |table1|
                                        if params.has_key?(table1.id.to_s)
                                            flag=1
                                            
                                            break
                                        end                               
                                    end
                                    end
                                end
                            end
                            end
            
                            if flag!=1
                                reservation1 = restaurant.reservations.create(user_id:current_account.accountable_id,date:date[:date],restaurant:restaurant)
                                if reservation1.save
                                    tables.each do |table|
                                        tableId = table.id.to_s
                                        if params.has_key?(tableId)
                                            flag=2
                                            reservation1.tables << table
                                        end    
                                    end
                                else
                                    render json: {errors: reservation1.errors.full_messages} , status: :unprocessable_entity 
                                    return
                                end
                            end
                            
                        end
                        if flag==1
                            render json: {message: "Table was already booked"} , status: :unprocessable_entity
                            return
                        elsif flag==0
                            reservation1.destroy
                            render json: {message: "No tables were selected"} , status: :unprocessable_entity
                            return
                        else
                            render json: {reservation: reservation1,reservation_table: reservation1.tables} , status: :ok
                            return
                        end
                    else
                        render json: {message: "Date was not selected"} , status: :unprocessable_entity
                        return
                    end
                else
                    render json: {message: "No tables is found for restaurant with this id #{params[:id]}"}, status: :not_found
                    return
                end
            end
        else
            render json: {message:"No restaurant is found with this id #{params[:id]}"}, status: :not_found
            return
        end     
    end

    def show
        if current_account and current_account.accountable_type=="User"
            user = User.find_by(id: current_account.accountable_id)
            reservations = user.reservations
            if reservations 
                latest_order = user.latest_order
                if latest_order
                    
                    render json: {reservations: reservations , latest_order: latest_order}
                else
                    render json: {message: "No latest order is found for current user"} , status: :no_content
                end
            else 
                render json: {message: "No reservation is found for current user"} , status: :no_content
            end
        elsif current_account and current_account.accountable_type=="Owner"
            owner = Owner.find(current_account.accountable_id)
            restaurants = owner.restaurants.all
            if restaurants 
                render json: restaurants , status: :ok
            else
                render json: {message:"No restaurants available"}
            end 
        end
    end


    def update
        reservation = Reservation.find_by(id: params[:reservation_id])
        if reservation
            tables = reservation.restaurant.tables 
            date = reservation.date

            if params.has_key?("table_book")

                reservations = Reservation.where(restaurant_id:reservation.restaurant.id)
                update_table = reservation.restaurant.tables.find(params.require(:table_book))
                flag=0

        
                if reservations && reservations.each do |reservation|
                    if reservation.tables.length!=0 && reservation.tables.each do |table|
                        
                        table2 = reservation.restaurant.tables.find(table.id)
                        b = reservation.date
                        if table2 == update_table &&  b.to_s == date.to_s
                            flag=1
                            break
                        end
                    end
                    end
                end
                end

                if flag==1
                    render json: {message:"Table was already booked"} , status: :unprocessable_entity
                else
                    reservation.tables << update_table
                    render json: reservation.tables , status: :ok

                end
                
            else
                render json: {message:"Fill all the details"} , status: :unprocessable_entity
            end  
        else 
            render json: {message: "No reservation is found with id #{params[:reservation_id]}"} , status: :not_found
        end
    end

    def destroy_each
        reservation = Reservation.find_by(id: params[:reservation_id])
        if reservation
            table = reservation.tables.find_by(id: params[:table_id])
            if table
                reservation.tables.delete(table)
                if reservation.save
                   
                    if reservation.tables.length==0 
                        reservation.destroy
                        render json: {message: "Reservation is destroyed.since there is no tables.."} , status: :see_other
                        return
                    end
                    render json: {reservation: reservation , reservation_table: reservation.tables} , status: :see_other
                else
                    render json: {errors: reservation.errors.full_messages } , status: :unprocessable_entity
                end
                
            else
                render json: {message: "No table is found with id #{params[:table_id]}"} , status: :not_found
            end
        else
            render json: {message: "No reservation is found with id #{params[:reservation_id]}"} , status: :not_found
        end
    end

    def destroy
        reservation = Reservation.find_by(id: params[:reservation_id])
        if reservation 
            tables = reservation.tables
            if reservation.order
                tables.each do |table|
                    reservation.tables.delete(table)
                end
                reservation.save
                
            else
                reservation.destroy
            end
            render json: {message: "Tables are deleted successfully"} , status: :see_other
        else
            render json: {message: "No reservation is found with id #{params[:reservation_id]}"} , status: :not_found
        end
    end

    private 
   def is_user
        unless current_account and current_account.accountable_type == "User"
            if current_account
                render json:{message: "You are not authorized !" } , status: :forbidden 
            else
                render json:{message: "You are not singed in  !" } , status: :unauthorized 
            end
        end
   end

    def is_user_table
        reservation = Reservation.find_by(id: params[:reservation_id])
        if reservation

app/views/table_bookeds/edit.html.erb
<h1>Edit Reservation </h1>


<div class="book_table bg-light text-dark">

        <%= form_tag(reservation_table_update_path(id:@reservation.restaurant_id,reservation_id:@reservation), method: "post") do |f|%>
                
                <div class="row row-cols-2">
                        <%if @tables_all && @tables_all.each do |table| %>
                                <div class="col">
                                <%= radio_button_tag(:table_book, table.id) %>
                                <%= label_tag(:reservation_table, table.name) %>
                                <p>Members occupy table : <%= table.member %></p>
                                </div>
                        <% end %>
                        <% end %>
                </div>
                <%= submit_tag "submit",class:"btn btn-success my-3 btn-sm w-100" %>
                
                <% @tables.each do |table| %>
                        <div class="row" >
                            <div class="col-9">
                                <p>Table Name : <%= table.name %></p>
                                <p>Members : <%= table.member %></p>
                            </div>
                            <%= link_to "Destroy", reservation_table_each_delete_path(reservation_id:@reservation,id:@reservation.restaurant_id,table_id:table.id), data: {
                                                turbo_method: :delete,
                                                turbo_confirm: "Are you sure?"
                                            } , class:"col btn btn-danger btn-sm h-50" %>
                        </div>
                        <hr>
                    <% end %>
        <% end %>
</div>

app/views/table_bookeds/show.html.erb
<%= stylesheet_link_tag 'table' %>

<% if account_signed_in? and current_account.accountable_type=="User" and @latest_order%>
    <h1>Latest Order <h1>

    <div class="card mb-3" style="max-width: 540px;margin-left:23%">
      <div class="row g-0">
        <div class="col-md-5 d-flex align-items-center">
          <%= image_tag(@latest_order.reservation.restaurant.images, style: "width: 100%; height: 200px;") %>
        </div>
        <div class="col-md-7">
          <div class="card-body" style="font-size:20px">

            <h5 class="card-title" style="text-decoration:underline;"><%= @latest_order.reservation.restaurant.name.upcase %></h5>
          
            <% @latest_order.order_items.each do |item| %>

              <p class="card-text mt-2">Menu Item: <%= item.name %></p>
              <p class="card-text">Quantity : <%= item.quantity%></p>
              
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<h1>My Reservations </h1>

<div class="show_reservation">

    <% @reservations.each do |reservation| %>
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">

          <div class="col-md-5 d-flex align-items-center">
            <%= image_tag(reservation.restaurant.images , style: "width: 100%; height: 200px;") %>
          </div>

          <div class="col-md-7">
            <div class="card-body">

              <h5 class="card-title" style="text-decoration:underline;"><%= reservation.restaurant.name.upcase %></h5>
              <div>

                <% if account_signed_in? and current_account.accountable_type=="Owner" %>
                  <p class="card-text">User name : <%= reservation.user.account.name %> </p>
                  <p class="card-text">Contact no: <%= reservation.user.account.contact %> </p>
                <% end %>

                <% if reservation.tables.length!=0 %>
                <p class="card-title" >Tables:</p>
                  <% reservation.tables.each do |table| %>
                    <p class="card-text">Table name : <%= table.name %></p>
                  <% end %>
                  <p class="card-text">Date : <%= reservation.date %></p>
                    <% if account_signed_in? and current_account.accountable_type=="User" %>
                      <%= link_to "edit" , reservation_table_edit_url(id:reservation.restaurant_id , reservation_id:reservation.id) , class:"btn btn-primary btn-sm mr-5" %>
                      <%= link_to "Destroy", reservation_table_delete_url(reservation_id:reservation,id:reservation.restaurant_id), data: {
                                      turbo_method: :delete,
                                      turbo_confirm: "Are you sure?"
                                    } ,  class:"btn btn-danger btn-sm mr-5"%>
                    <% end %>
                <% end %>
            
                <% if reservation.order %>

                <p class="card-title mt-3" >Orders:</p>


                <% reservation.order.order_items.each do |item| %>
                 

                  <p class="card-text mt-2">Menu Item: <%= item.name %></p>
                  <p class="card-text">Quantity : <%= item.quantity%></p>
                  
                <% end %>
                <% if account_signed_in? and current_account.accountable_type == "User" %>
                
                  <%= link_to "edit" , reservation_order_edit_url(id:reservation.restaurant_id , reservation_id:reservation.id) ,  class:"btn btn-primary btn-sm mr-5"%>
                  <%= button_to "Destroy", reservation_order_delete_path(id:reservation.restaurant_id,reservation_id:reservation.id), class:"btn btn-danger btn-sm mr-5",method: :delete%>
                
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    


</div>

app/views/table_bookeds/table.html.erb
<%= stylesheet_link_tag 'table' %>
<h1>Book Table...</h1>
<%= link_to "Book tables for today" ,  today_tables_path  ,class:"btn btn-dark today_table"%>

<div class="book_table bg-light text-dark">

        <%= form_tag(reservation_table_confrim_path(id:@restaurant,type:@type), method: "post") do |f|%>
                <div class="row row-cols-2">
                        <% if @tables.length == 0 %>
                                <h2>OOPS!..No table available</h2>
                        <% else %>
                                <% @tables.each do |table| %>
                                        <div class="col">
                                        <p><%= check_box_tag table.id %>
                                        <%= label_tag(table.id, table.name) %></p>
                                        
                                        <p>Members occupy table : <%= table.member %></p>
                                        </div>
                                <% end %>
                        <% end %>
                </div>
                <hr>
                <%= label_tag(:date, Date,class:"form-label") %>
                <%= date_field(:date_id, :date,class:"form-control") %>
                <%= submit_tag "submit",class:"btn btn-success my-3 btn-sm w-100" %>
                
        <% end %>
</div>

app/views/table_bookeds/today_table.html.erb
<%= stylesheet_link_tag 'table' %>
<h1>Book Table...</h1>

<div class="book_table bg-light text-dark">

        <%= form_tag(today_tables_confrim_path ,method: "post") do |f|%>
                <div class="row row-cols-2">
                        <% if @tables and @tables.length!=0 %>
                                <% @tables.each do |table| %>
                                        <div class="col">
                                        <p><%= check_box_tag table.id %>
                                        <%= label_tag(table.id, table.name) %></p>
                                        
                                        <p>Members occupy table : <%= table.member %></p>
                                        </div>
                                <% end %>
                        <% else %>
                                <h2>OOPS!..No table available</h2>
                        <% end %>
                </div>
                <hr>
                <%= submit_tag "submit",class:"btn btn-success my-3 btn-sm w-100" %>
                
        <% end %>
</div>