config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

  devise_for :accounts,controllers: {
    sessions: 'accounts/sessions',
    password: 'accounts/passwords',
    registrations: 'accounts/registrations',
    confirmations: 'accounts/confirmations'
  }
  
  root "restaurants#index"

  resources :restaurants do
    resources :tables
    resources :menu_items
  end


post "restaurant/:id/reservations/index" , to: "reservations#index" , as:"reservation_index"

delete "restaurant/:id/reservations/:reservation_id/order", to: "orders#destroy" , as:"reservation_order_delete"

#table booking
  get "restaurant/:id/reservations/:type" , to: "table_bookeds#table" , as:"reservation_table"
  post "restaurant/:id/reservations/:type/confrim", to: "table_bookeds#confrim" , as:"reservation_table_confrim"
  get "reservations/show" , to: "table_bookeds#show" , as:"reservation_show"
  delete "restaurant/:id/reservations/:reservation_id", to: "table_bookeds#destroy" , as:"reservation_table_delete"
  delete "restaurant/:id/reservations/:reservation_id/:table_id", to: "table_bookeds#destroy_each" , as:"reservation_table_each_delete"
  get "restaurant/:id/today" , to: "table_bookeds#today_table" , as:"today_tables"
  post "restaurant/:id/today_confrim" , to: "table_bookeds#today_table_confrim" , as:"today_tables_confrim"

  get "restaurant/:id/reservations/:reservation_id/edit" , to: "table_bookeds#edit" , as:"reservation_table_edit"
  post "restaurant/:id/reservations/:reservation_id/update" , to: "table_bookeds#update" , as:"reservation_table_update"

#food ordering
  get "restaurant/:id/reservations/:reservation_id/food" , to: "orders#food" , as:"reservation_food"
  post "restaurant/:id/reservations/:reservation_id/food/confrim", to: "orders#confrim" , as:"reservation_food_confrim"
  get "restaurant/:id/reservations/:reservation_id/order/edit" , to: "orders#edit" , as:"reservation_order_edit"
  patch "restaurant/:id/reservations/:reservation_id/order/update" , to: "orders#update" , as:"reservation_order_update"

 #order items 

  delete "restaurant/:id/reservations/:reservation_id/order/:order_item_id", to: "order_items#destroy" , as:"reservation_order_items_delete"
  post "restaurant/:id/reservations/:reservation_id/order/:order_id/new", to: "order_items#new" , as:"reservation_order_items_new"

  #ratings
  get "restaurant/:id/reservations/:reservation_id/rating" , to:"ratings#new" , as:"reservation_rating_new"
  post "restaurant/:id/reservations/:reservation_id/rating_create" , to:"ratings#create" , as:"reservation_rating_create"
   
  # for api

  namespace :api ,default: {format: :json} do
  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    

    devise_for :accounts,controllers: {
      sessions: 'accounts/sessions',
      password: 'accounts/passwords',
      registrations: 'accounts/registrations',
      confirmations: 'accounts/confirmations'
    }
    
    root "restaurants#index"

    resources :restaurants do
      resources :tables
      resources :menu_items
    end


  post "restaurant/:id/reservations/index" , to: "reservations#index" , as:"reservation_index"

  delete "restaurant/:id/reservations/:reservation_id/order", to: "orders#destroy" , as:"reservation_order_delete"

  #table booking
    get "restaurant/:id/reservations/:type" , to: "table_bookeds#table" , as:"reservation_table"
    post "restaurant/:id/reservations/:type/confrim", to: "table_bookeds#confrim" , as:"reservation_table_confrim"
    get "reservations/show" , to: "table_bookeds#show" , as:"reservation_show"
    delete "restaurant/:id/reservations/:reservation_id", to: "table_bookeds#destroy" , as:"reservation_table_delete"
    delete "restaurant/:id/reservations/:reservation_id/:table_id", to: "table_bookeds#destroy_each" , as:"reservation_table_each_delete"

    get "restaurant/:id/reservations/:reservation_id/edit" , to: "table_bookeds#edit" , as:"reservation_table_edit"
    post "restaurant/:id/reservations/:reservation_id/update" , to: "table_bookeds#update" , as:"reservation_table_update"

  #food ordering
    get "restaurant/:id/reservations/:reservation_id/food" , to: "orders#food" , as:"reservation_food"
    post "restaurant/:id/reservations/:reservation_id/food/confrim", to: "orders#confrim" , as:"reservation_food_confrim"
    get "restaurant/:id/reservations/:reservation_id/order/edit" , to: "orders#edit" , as:"reservation_order_edit"
    patch "restaurant/:id/reservations/:reservation_id/order/update" , to: "orders#update" , as:"reservation_order_update"

  #order items 

    delete "restaurant/:id/reservations/:reservation_id/order/:order_item_id", to: "order_items#destroy" , as:"reservation_order_items_delete"
    post "restaurant/:id/reservations/:reservation_id/order/:order_id/new", to: "order_items#new" , as:"reservation_order_items_new"

    #ratings
    get "restaurant/:id/reservations/:reservation_id/rating" , to:"ratings#new" , as:"reservation_rating_new"
    post "restaurant/:id/reservations/:reservation_id/rating_create" , to:"ratings#create" , as:"reservation_rating_create"
    

    #custom api

    get "restaurant/:city", to:"restaurants#restaurant_city"
    get "highest_reservation" , to:"restaurants#restaurant_highest_reservations"
    get "restaurant/:id/users" , to: "restaurants#restaurant_users"
    get  "highest_order" , to:"orders#highest_item"
    get "highest_reservation/user" , to:"restaurants#highest_reservation_user"
    
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    paginates_per 3
    has_many :tables , dependent: :destroy
    has_many :menu_items , dependent: :destroy
    has_many :reservations , dependent: :destroy
    belongs_to :owner
    has_many :ratings,as: :rateable
    has_one_attached :images ,dependent: :destroy
    has_many :users , through: :reservations

    #validations

    validates :name, presence:true , length: { minimum: 3 , maximum: 25}
    validates :address , presence:true ,length: { minimum: 5 , maximum: 30} 
    validates :city  , presence: true ,  length: { minimum: 4 , maximum: 15} 
    validates :contact , presence:true, length: { minimum: 10 , maximum: 10} , numericality: { only_integer: true, greater_than: 0 }
    validate :unique_fields_combination

    def unique_fields_combination
      existing_table = Restaurant.find_by(name: name, address: address, city: city ,contact: contact )
      if existing_table && (new_record? || existing_table.id != id)
        errors.add(:name, 'Can not create same restaurant again')
      end
    end
    before_create :make_lower

    def make_lower
      self.name.downcase!
      self.city.downcase!
    end

    # scope
    scope :rating_greater_than_75, -> { where('restaurants.id IN (?)', Restaurant.pluck(:id).select { |id| Restaurant.find(id).avg_ratings >= 75 }) }
    
    scope :most_reserved, -> {
      where(id: Reservation.select('restaurant_id::bigint').group('restaurant_id').order('COUNT(reservations.id) DESC').limit(1))
    }
     

    def avg_ratings
      average_rating = ratings.average(:value)
      if average_rating
      formatted_average_rating =  sprintf('%.2f', average_rating)
      formatted_average_rating.to_f
      else
        0
      end
    end


end

app/controllers/api/restaurants_controller.rb
class Api::RestaurantsController < Api::ApiController
  before_action :is_owner ,only: [ :create,:edit,:update,:destroy]
  before_action :is_restaurant_owner , only: [:edit,:update,:destroy]

  def index
    if current_account and current_account.accountable_type=="Owner"
      restaurants = Restaurant.where(owner_id:current_account.accountable_id)
      if restaurants.length != 0 
          render json: restaurants, status: :ok
      else
        render json: {message:"No restaurants available" }, status: :no_content
      end
    else 
      restaurants = Restaurant.all 
      if restaurants.length != 0 
        render json: restaurants, status: :ok
      else
        render json: {message:"No restaurants available" }, status: :no_content
      end
    end
  end

  def show
    restaurant = Restaurant.find_by(id: params[:id])
    if restaurant
      render json: restaurant, status: :ok
    else
      render json: {message:"No restaurant is found with id #{params[:id]}"}, status: :not_found
    end
  end


  def create 
    owner = Owner.find_by(id: current_account.accountable_id)
    if owner 
      restaurant = owner.restaurants.create(restaurant_params)
      # byebug
      if restaurant.save
        render json: restaurant , status: :created
      else 
        render json: {errors: restaurant.errors.full_messages} , status: :unprocessable_entity
      end
    else
      render json: {message:"No owner is found with this id #{current_account.accountable_id}"} , status: :not_found
    end
  end


  def update
    restaurant = Restaurant.find_by(id: params[:id])
    if restaurant
      restaurant.update(restaurant_params)
      if restaurant.save
        render json: restaurant , status: :ok
      else 
        render json: {errors: restaurant.errors.full_messages} , status: :unprocessable_entity
      end
    else
      render json: {message:"No restaurant is found with id #{params[:id]}"} , status: :not_found
    end
  end

  def destroy
    restaurant = Restaurant.find_by(id: params[:id])
    if restaurant
      if restaurant.destroy
        render json: restaurant , status: :see_other
      else 
        render json: {errors: restaurant.errors.full_messages } , status: :unprocessable_entity
      end
    else
      render json: {message:"No restaurant is found with id #{params[:id]}"} , status: :not_found
    end
  
  end

  def restaurant_city
    city = params[:city].downcase
    restaurants  = Restaurant.where("city LIKE ?", "%#{city}%")
    if restaurants.length!=0
      render json: restaurants , status: :ok
    else
      render json: {message: "No restaurant is available with city as #{city}"} , status: :not_found
    end
  end

  def restaurant_highest_reservations
    restaurants = Restaurant.joins(:reservations)
    .group('restaurants.id')
    .order('COUNT(reservations.id) DESC')
    .first

    if restaurants
      render json:restaurants , status: :ok
    else 
      render json: {message: "No restaurants found"} , status: :not_found
    end

  end
  
  def restaurant_users
    restaurant = Restaurant.find_by(id: params[:id])
    if restaurant
      restaurant_users = restaurant.users
      if restaurant_users.length!=0
        render json: restaurant_users , status: :ok
      else
        render json: {message:"No users available"} , status: :not_found
      end
    else
      render json: {message:"no restaurant is found with given id"} , status: :not_found
    end
  end

  def highest_reservation_user
    users = User.joins(:reservations)
    .group('users.id')
    .order('COUNT(reservations.id) DESC')
    .first

    if users
      render json: users , status: :ok
    else
      render json: {message:"No users "} , status: :not_found
    end
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name,:contact,:address,:city,:images)
    end

  private 
  def is_owner
      unless current_account and current_account.accountable_type=="Owner"
        if current_account
          render json:{message: "You are not authorized !" } , status: :forbidden
        else
          render json:{message: "You are not signed in !" } , status: :unauthorized
        end
      end
  end

  def is_restaurant_owner 
    restaurant = Restaurant.find_by(id: params[:id])
    if restaurant
      unless current_account and current_account.accountable_id==restaurant.owner_id
        render json:{message: "You are not authorized !" } , status: :forbidden
      end
    else
      render json: {message:"No restaurant is found with id #{params[:id]}"} , status: :not_found
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :is_owner ,only: [ :new,:create ]
  before_action :is_restaurant , only: [:show,:edit,:update,:destroy]
  before_action :is_restaurant_owner , only: [:edit,:update,:destroy]
 

  def index
    @restaurants = Restaurant.all
    @index = false

    if account_signed_in? and current_account.accountable_type=="Owner"
      unless params[:name]
        @restaurants = Restaurant.all.page(params[:page])
        @index = true
      else 
        if params[:name] and params[:name].length!=0
          field = params[:field]
          name = params[:name].downcase
          if field=="Name"
            @restaurants = Restaurant.where("name LIKE ?", "%#{name}%")
          elsif field=="City"
            @restaurants = Restaurant.where("city LIKE ?", "%#{name}%")
          elsif field=="MenuItem"
            @restaurants = Restaurant.joins(:menu_items).where("menu_items.name LIKE ?", "%#{name}%")
          end
        end
      end
      @restaurants = @restaurants.where(owner_id:current_account.accountable_id)
    else
      unless params[:name]
        @restaurants = Restaurant.left_outer_joins(:tables, :menu_items)
        .where('tables.id IS NOT NULL OR menu_items.id IS NOT NULL')
        .distinct.page(params[:page])
        @index = true
      else 
        if params[:name] and params[:name].length!=0
          field = params[:field]
          name = params[:name].downcase
          
          if field=="Name"
            @restaurants = Restaurant.left_outer_joins(:tables, :menu_items)
                          .where('tables.id IS NOT NULL OR menu_items.id IS NOT NULL')
                          .where("restaurants.name LIKE ?", "%#{name}%")
                          .distinct
          elsif field=="City"
            @restaurants = Restaurant.left_outer_joins(:tables, :menu_items)
                          .where('tables.id IS NOT NULL OR menu_items.id IS NOT NULL')
                          .where("restaurants.city LIKE ?", "%#{name}%")
                          .distinct
          elsif field=="MenuItem"
            @restaurants = Restaurant.left_outer_joins(:tables, :menu_items)
                          .where('tables.id IS NOT NULL OR menu_items.id IS NOT NULL')
                          .where("menu_items.name LIKE ?", "%#{name}%")
                          .distinct
          end 
        end
      end    
    end 
  end

  def show 
  end
  # modeling and demodeling , trasormation model ,image procesing

  def new 
    @restaurant = Restaurant.new()
  end

  def create 
    @owner = Owner.find(current_account.accountable_id)
    @restaurant = @owner.restaurants.create(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant , notice:"Created New Restaurant"
    else
      flash.now[:alert] = 'Failed to save restaurant'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant , notice:"Updated successfully"
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name,:contact,:address,:city,:images)
  end
  
end


def is_owner
    unless account_signed_in? and current_account.accountable_type=="Owner"
      flash[:notice] = "Owner permissions only!!"
      if account_signed_in?
        redirect_to root_path
      else
        redirect_to new_account_session_path
      end
    end
  end

def is_restaurant_owner 
  @restaurant = Restaurant.find_by(id: params[:id])
  unless account_signed_in? and current_account.accountable_id==@restaurant.owner_id
    flash[:notice] = "Owner permissions only!!"
    if account_signed_in?
      redirect_to root_path
    else
      redirect_to new_account_session_path
    end
  end
end

def is_restaurant
  if @restaurant = Restaurant.find_by(id: params[:id])
    @restaurant
  else
    redirect_to root_path , notice:"No restaurant is available with given id"
  end
end

app/views/restaurants/_form.html.erb
<%= stylesheet_link_tag 'restaurant' %>

<%= form_with model: restaurant , class:"restaurant_form bg-light text-dark" do |form|  %>


  <div class="mb-3">
    <%= form.label :name ,class:"form-label" %>
    <%= form.text_field :name , class:"form-control" , required:true %>
    <% restaurant.errors.full_messages_for(:name).each do |message| %>
      <div class="form-text"><%= message %></div>
    <% end %>
  </div>


  <div class="mb-3">
    <%= form.label :contact,class:"form-label" %>
      <%= form.text_field :contact , class:"form-control" , required:true %>
      <% restaurant.errors.full_messages_for(:contact).each do |message| %>
        <div class="form-text"><%= message %></div>
      <% end %>
  </div>


  <div class="mb-3">
    <%= form.label :address ,class:"form-label"%><br>
    <%= form.text_area :address , class:"form-control" , required:true  %>
    <% restaurant.errors.full_messages_for(:address).each do |message| %>
      <div class="form-text"><%= message %></div>
    <% end %>
  </div>
    
  <div class="mb-3">
    <%= form.label :city ,class:"form-label"%>
    <%= form.text_field :city  , class:"form-control" , required:true  %>
    <% restaurant.errors.full_messages_for(:city).each do |message| %>
      <div class="form-text"><%= message %></div>
    <% end %>
  </div>


  <div class="mb-3">
    <%= form.label :images ,class:"form-label"%>
    <%= form.file_field :images, multiple:false , class:"form-control" , required:true , accept: 'image/*'%>
    <% restaurant.errors.full_messages_for(:images).each do |message| %>
      <div class="form-text"><%= message %></div>
    <% end %>
  </div>

  <%= form.submit  "submit" , class:"btn btn-success my-3" %>
  
  <% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant details </h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<%= stylesheet_link_tag 'restaurant' %>

<h1>My Restaurants...</h1>

<div class="row row-cols-1 row-cols-md-3 g-4" >
    <% @restaurants.each do |restaurant| %>
        <div class="col" >
            <div class="card h-100" style="width: 19rem;">
                <%= image_tag(restaurant.images, style: "object-fit: contain; width: 100%; height: 100%" , class:"card-img-top") %>
                <div class="card-body">
                    <div class="card-text">
                        <p> <%= restaurant.name.upcase %> </p>
                        <p> <%= restaurant.address %> </p>
                        <p> <%= restaurant.city %> </p>
                        <p>ph.no: <%= restaurant.contact %> </p>
                        <%= link_to "show more" , restaurant ,class:"btn btn-dark"%>
                    </div>
                </div>
            </div>
        </div> 
    <% end %>
</div>
<% if @index %>
    <%=paginate @restaurants %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant...</h1>

<%= render "form" , restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col image">
      <%= image_tag(@restaurant.images, style: "object-fit: contain; width: 100%; height: 100%") %>
    </div>
    <div class="col restaurant_details">

      <h1><%= @restaurant.name.upcase %></h1>
      <p><%= @restaurant.address %></p>
      
      <p><%= @restaurant.city %></p>
      <p>ph.no:<%= @restaurant.contact %></p> 
      
      
     <% if account_signed_in? and current_account.accountable_type=="Owner" %>
        <%= link_to "Edit" , edit_restaurant_url , class:"btn btn-primary btn-sm mr-5"%>
        <%= link_to "Destroy", restaurant_path(@restaurant), data: {
                         turbo_method: :delete,
                         turbo_confirm: "Are you sure?"
                       } , class:"btn btn-danger btn-sm" %>
      <% end %>
     <br>
    </div>
  </div>
</div>


<h1>__Tables__</h1>
<% if @restaurant.tables.length==0 %>
  <% if account_signed_in? and current_account.accountable_type=="Owner" %>
    <h5>No tables were added!</h5>
  <% else %>
    <h5>Oops!..no table available..</h5>
  <% end %>
<% else %>
  <div class="row row-cols-1 row-cols-md-4 table_details">
  <% @restaurant.tables.each do |table| %>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
            <p>Table name: <%= table.name %></p>
            <p>Members occupy table:<%= table.member %></p>
            
            <% if account_signed_in? and current_account.accountable_type=="Owner" %>
              <%= link_to "Edit",  edit_restaurant_table_path(restaurant_id:@restaurant.id,id:table.id)  , class:" btn btn-primary btn-sm mr-10" %>
              <%= link_to "Destroy", restaurant_table_path(restaurant_id:@restaurant.id,id:table.id), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                              } , class:"btn btn-danger btn-sm"%>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<% end %>

<% if account_signed_in? and current_account.accountable_type=="Owner" %>
<div>
  <h2>Add new table </h2>
  <%= render "/tables/form" , restaurant: @restaurant %>
</div>
<% end %>

<h1>__Menu Items__</h1>
<% if @restaurant.menu_items.length==0 %>
  <% if account_signed_in? and current_account.accountable_type=="Owner" %>
    <h5>No menu items were added!</h5>
  <% else %>
    <h5>Oops!..no menu items available..</h5>
  <% end %>
<% else %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <% @restaurant.menu_items.each do |menu| %>
  <div class="col">
    <div class="card" style="width: 20rem; height:25rem">
      <%= image_tag(menu.images, style: "width: 100%; height: 80%",class:"card-img-top") %>
      <div class="card-body">
        <p>Name:&nbsp;&nbsp;<%= menu.name %></p>
        <p>Quantity:&nbsp;&nbsp;<%= menu.quantity %></p>
        <p>Rate:&nbsp;&nbsp;<%= menu.rate %></p>

      <% if account_signed_in? and current_account.accountable_type=="Owner" %>
        <%= link_to "Edit",  edit_restaurant_menu_item_path(restaurant_id:@restaurant.id,id:menu.id),class:"btn btn-primary btn-sm" %>
        <%= link_to "Destroy", restaurant_menu_item_path(restaurant_id:@restaurant.id,id:menu.id), data: {
                          turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } ,class:"btn btn-danger btn-sm" %>
      <% end %>
      </div>
    </div>
  </div>
  <% end %>
  </div>
<% end %>

<% if account_signed_in? and current_account.accountable_type=="Owner" %>
<div>
  <h2>Add new menu </h2>
  <%= render "/menu_items/form" , restaurant: @restaurant %>
</div>
<% end %>

<% if account_signed_in? and current_account.accountable_type=="User" %>

<h1>__choose options for reserving table and ordering food__</h1>

<%= form_tag(reservation_index_path(id: @restaurant) , method: "post" , class:"d-flex flex-column align-items-center") do %>

  <div class="form-check">
    <%= radio_button_tag(:reservation, "Table",class:"form-check-input") %>
    <%= label_tag(:reservation_table, "Table only",class:"form-check-label" ) %>
  </div>

  <div class="form-check">
    <%= radio_button_tag(:reservation, "Food",class:"form-check-input") %>
    <%= label_tag(:reservation_food, "Food only",class:"form-check-label") %>
  </div>

  <div class="form-check">
    <%= radio_button_tag(:reservation, "Table with food",class:"form-check-input") %>
    <%= label_tag(:reservation_both, "Table with food",class:"form-check-label") %>
  </div>
  
  <%= submit_tag "submit",class:"btn btn-success my-3 btn-sm" %>

<% end %>
<% end %>