config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

  devise_for :accounts,controllers: {
    sessions: 'accounts/sessions',
    password: 'accounts/passwords',
    registrations: 'accounts/registrations',
    confirmations: 'accounts/confirmations'
  }
  
  root "restaurants#index"

  resources :restaurants do
    resources :tables
    resources :menu_items
  end


post "restaurant/:id/reservations/index" , to: "reservations#index" , as:"reservation_index"

delete "restaurant/:id/reservations/:reservation_id/order", to: "orders#destroy" , as:"reservation_order_delete"

#table booking
  get "restaurant/:id/reservations/:type" , to: "table_bookeds#table" , as:"reservation_table"
  post "restaurant/:id/reservations/:type/confrim", to: "table_bookeds#confrim" , as:"reservation_table_confrim"
  get "reservations/show" , to: "table_bookeds#show" , as:"reservation_show"
  delete "restaurant/:id/reservations/:reservation_id", to: "table_bookeds#destroy" , as:"reservation_table_delete"
  delete "restaurant/:id/reservations/:reservation_id/:table_id", to: "table_bookeds#destroy_each" , as:"reservation_table_each_delete"
  get "restaurant/:id/today" , to: "table_bookeds#today_table" , as:"today_tables"
  post "restaurant/:id/today_confrim" , to: "table_bookeds#today_table_confrim" , as:"today_tables_confrim"

  get "restaurant/:id/reservations/:reservation_id/edit" , to: "table_bookeds#edit" , as:"reservation_table_edit"
  post "restaurant/:id/reservations/:reservation_id/update" , to: "table_bookeds#update" , as:"reservation_table_update"

#food ordering
  get "restaurant/:id/reservations/:reservation_id/food" , to: "orders#food" , as:"reservation_food"
  post "restaurant/:id/reservations/:reservation_id/food/confrim", to: "orders#confrim" , as:"reservation_food_confrim"
  get "restaurant/:id/reservations/:reservation_id/order/edit" , to: "orders#edit" , as:"reservation_order_edit"
  patch "restaurant/:id/reservations/:reservation_id/order/update" , to: "orders#update" , as:"reservation_order_update"

 #order items 

  delete "restaurant/:id/reservations/:reservation_id/order/:order_item_id", to: "order_items#destroy" , as:"reservation_order_items_delete"
  post "restaurant/:id/reservations/:reservation_id/order/:order_id/new", to: "order_items#new" , as:"reservation_order_items_new"

  #ratings
  get "restaurant/:id/reservations/:reservation_id/rating" , to:"ratings#new" , as:"reservation_rating_new"
  post "restaurant/:id/reservations/:reservation_id/rating_create" , to:"ratings#create" , as:"reservation_rating_create"
   
  # for api

  namespace :api ,default: {format: :json} do
  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    

    devise_for :accounts,controllers: {
      sessions: 'accounts/sessions',
      password: 'accounts/passwords',
      registrations: 'accounts/registrations',
      confirmations: 'accounts/confirmations'
    }
    
    root "restaurants#index"

    resources :restaurants do
      resources :tables
      resources :menu_items
    end


  post "restaurant/:id/reservations/index" , to: "reservations#index" , as:"reservation_index"

  delete "restaurant/:id/reservations/:reservation_id/order", to: "orders#destroy" , as:"reservation_order_delete"

  #table booking
    get "restaurant/:id/reservations/:type" , to: "table_bookeds#table" , as:"reservation_table"
    post "restaurant/:id/reservations/:type/confrim", to: "table_bookeds#confrim" , as:"reservation_table_confrim"
    get "reservations/show" , to: "table_bookeds#show" , as:"reservation_show"
    delete "restaurant/:id/reservations/:reservation_id", to: "table_bookeds#destroy" , as:"reservation_table_delete"
    delete "restaurant/:id/reservations/:reservation_id/:table_id", to: "table_bookeds#destroy_each" , as:"reservation_table_each_delete"

    get "restaurant/:id/reservations/:reservation_id/edit" , to: "table_bookeds#edit" , as:"reservation_table_edit"
    post "restaurant/:id/reservations/:reservation_id/update" , to: "table_bookeds#update" , as:"reservation_table_update"

  #food ordering
    get "restaurant/:id/reservations/:reservation_id/food" , to: "orders#food" , as:"reservation_food"
    post "restaurant/:id/reservations/:reservation_id/food/confrim", to: "orders#confrim" , as:"reservation_food_confrim"
    get "restaurant/:id/reservations/:reservation_id/order/edit" , to: "orders#edit" , as:"reservation_order_edit"
    patch "restaurant/:id/reservations/:reservation_id/order/update" , to: "orders#update" , as:"reservation_order_update"

  #order items 

    delete "restaurant/:id/reservations/:reservation_id/order/:order_item_id", to: "order_items#destroy" , as:"reservation_order_items_delete"
    post "restaurant/:id/reservations/:reservation_id/order/:order_id/new", to: "order_items#new" , as:"reservation_order_items_new"

    #ratings
    get "restaurant/:id/reservations/:reservation_id/rating" , to:"ratings#new" , as:"reservation_rating_new"
    post "restaurant/:id/reservations/:reservation_id/rating_create" , to:"ratings#create" , as:"reservation_rating_create"
    

    #custom api

    get "restaurant/:city", to:"restaurants#restaurant_city"
    get "highest_reservation" , to:"restaurants#restaurant_highest_reservations"
    get "restaurant/:id/users" , to: "restaurants#restaurant_users"
    get  "highest_order" , to:"orders#highest_item"
    get "highest_reservation/user" , to:"restaurants#highest_reservation_user"
    
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@1,300&family=Lato:ital@1&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="font-family: 'Lato', sans-serif;">
      <div class="container-fluid"> 
        <a class="navbar-brand" href="#">Restaurant Reservation</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Home" , root_path , class:"nav-link active" %>
            <% if account_signed_in? and current_account.accountable_type=="Owner" %>
              <%= link_to "Add new restaurant" ,  new_restaurant_url , class:"nav-link" %>
            <% end %>
            <%= link_to "Show my reservations" , reservation_show_url , class:"nav-link" %>
            <% if account_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_account.name %>
              </a>
              <ul class = "dropdown-menu" aria-labelledby="navbarDropdown">
                <% if false %>
                  <li><%= button_to "Edit profile" ,   edit_account_registration_path  , method: :get, class:"nav-link",style:"border:none; background-color:white; color:black;" %>
                  </li>
                <% end %>
                <li><%= button_to "Sign out" ,  destroy_account_session_path , method: :delete, class:"nav-link ",style:"border:none; background-color:white; color:black;" %>
                </li>
              </ul>
            </li>

            <% else %>
              <%= link_to "login" , new_account_session_path , class:"nav-link" %>
            <% end %>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              search
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">search by different fields</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                  <%=form_with url:root_path, class:"row",method: :get do |f|%>
                    <div class="form-group my-3 ">

                        <%=f.text_field :name ,class:"form-control",placeholder:"Enter search word.."%>
                    </div>
                    <div class="my-2">
                      <label>Enter field by which search needs to be applied</label>
                      <%= f.select(:field,[['Name', 'Name'], ['MenuItem', 'MenuItem'], ['City', 'City'] ],{},{:class=>"form-select"})%>
                    </div>
                    <div class="my-3">
                      <%=f.submit "Search",class:"btn btn-success w-100"%></button>    
                    </div>
                
                <%end%>
                  </div>
                   
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </nav>
    <div class="container" >
      <% if flash[:notice] %>
          <div class="alert alert-warning alert-dismissible fade show w-50" role="alert" style="margin-left:25%;margin-top:2%;">
                  <%= flash[:notice] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>